services:
  - type: web
    name: humedad-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app.server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
